STATISTIC.hsakmt_sampler.metrics=[model.gpu.hsakmt]
STATISTIC.hsakmt_sampler.counters=[.*jitcu.*]
STATISTIC.hsakmt_sampler.dumper=hsakmt_dumper
STATISTIC.hsakmt_dumper.file=hsakmt_counters.csv
STATISTIC.hsakmt_dumper.type=csv
COMPONENT.jitcu_itrace.wave_type=ALL
COMPONENT.jitcu_itrace.wave_id=-1
COMPONENT.jitcu_itrace.enable_gvlog=false
COMPONENT.jitcu_itrace.disable_wave_start=false
COMPONENT.jitcu_itrace.dump_after_rt=false
COMPONENT.jitcu_itrace.all_lanes=false
COMPONENT.jitcu_itrace.dump_rsrc_desc=false
COMPONENT.jitcu_itrace.dump_matrix=false
COMPONENT.jitcu_plugins.all_operand_lanes=false
COMPONENT.jitcu.enable_time_slicing=true
COMPONENT.shader_complex.random_seed=2419679752034188
COMPONENT.shader_complex.exec_order=0
COMPONENT.shader_complex.raw_shader_dump_path=
COMPONENT.shader_complex.lds_oob_strict_level=0
COMPONENT.shader_complex.debug_barier_semaphore=false
COMPONENT.shader_complex.use_fast_float=false
COMPONENT.shader_complex.use_wmma_simd_matmul=false
COMPONENT.shader_complex.barrier_checks_strict=false
COMPONENT.shader_complex.use_avx=false
COMPONENT.shader_complex.use_vmat=false
COMPONENT.shader_complex.use_wmma_fast_gather=false
COMPONENT.shader_complex.time_instructions=false
COMPONENT.shader_complex.sh_mem_config_unaligned=true
COMPONENT.shader_complex.use_jit=false
COMPONENT.shader_complex.validate_gprs=false
COMPONENT.shader_complex.force_mem_dep_check=false
COMPONENT.shader_complex.validate_gprs_strict=false
